/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.umelab.selenium;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class App {
    private static String url = "https://www.river.go.jp/kawabou/pcfull/tm?itmkndCd=6&ofcCd=22039&obsCd=6&isCurrent=true&fld=0";

    public void getConnection() {
        WebDriver driver = new ChromeDriver();
        driver.get(url);

        String title = driver.getTitle();
        System.out.println("Web from: " + title);  

        driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

        // WebElement name = driver.findElement(By.className(".pl-2 .col .tm-pc-detail-border-line .pt-1 .tm-pc-detail-info-curt-title"));
        WebElement name = driver.findElement(By.className("tm-pc-detail-frame-info-rvrnm"));
        WebElement temp = driver.findElement(By.className("tm-pc-detail-info-curt-value"));
        System.out.println("content: " + name.getText());
        System.out.println("temp: " + temp.getText());
        
        driver.quit();
    }

    public static void main(String[] args) {
        App app = new App();
        app.getConnection();
    }
}
