/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.umelab.designpattern;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Animal monkey = new Monkey();
        Animal lion = new Lion();

        Speak speak = new Speak();

        monkey.accept(speak);
        lion.accept(speak);

        Move move = new Move();
        monkey.accept(move);
        lion.accept(move);
    }
}
